platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: c3b1c191256badfcdac2db6f4381278e9b260636

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: ac7826eff7480635ed6b16e76820ef280f7292d1

- name: Ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 36e529211a2fa9c8f3f61fdd141ca37e2cc1c3da

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 80c4447d0c6866d5e76de61be596221eec856503

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: master
  commit: b5f64f676aff69e760c994a869bb6feb187a38e9

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: f2c15c5aeae22363a1f6899bddf39c357ab4da64

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: dd167974c5e9ba96f6216f856b2009164a18caa8
