platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: e92138977effa3c76940417e6d6eb9ba6f2c3c2c

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: 113aaef3d4838fd1665d88756fe906f56e3eb402

- name: Ubuntu
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 4aadb7291e4a412cd19cdb89298c0d28dada7958

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: bc2c43aec9061d851d2e83859c101aa492e8bd53

- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: master
  commit: a1311ff5c30358908bcaece60b15a6b1f92a57cb

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 598321a8cd871f38d455e0e7e50c5bba9907359e

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 39e9dfa066b69b948026f7bb3e3fdbb72169e7c9
