// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef UI_AI_CHAT_H
#define UI_AI_CHAT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ai_chat
extern void ui_ai_chat_screen_init(void);
extern void ui_ai_chat_screen_destroy(void);
extern void ui_event_ai_chat(lv_event_t * e);
extern lv_obj_t * ui_ai_chat;
extern lv_obj_t * ui_left_eye;
extern lv_obj_t * ui_right_eye;
extern lv_obj_t * ui_chat_text;
extern lv_obj_t * ui_red_ring;
extern lv_obj_t * ui_mic_icon;

// CUSTOM FUNCTIONS
void ui_ai_chat_set_red_ring_visible(bool visible);
void ui_ai_chat_update_text(const char *text);

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

