// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#include "../ui.h"

lv_obj_t * ui_ai_chat = NULL;
lv_obj_t * ui_left_eye = NULL;
lv_obj_t * ui_right_eye = NULL;
lv_obj_t * ui_chat_text = NULL;
lv_obj_t * ui_red_ring = NULL;
// event funtions
void ui_event_ai_chat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE) {
        lv_indev_wait_release(lv_indev_active());
        ai_chat_event_callback(e);
    }
}

// build funtions

void ui_ai_chat_screen_init(void)
{
    if (ui_ai_chat != NULL) {
        return;
    }

    ui_ai_chat = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ai_chat, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_ai_chat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ai_chat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_left_eye = lv_obj_create(ui_ai_chat);
    lv_obj_remove_style_all(ui_left_eye);
    lv_obj_set_width(ui_left_eye, 140);
    lv_obj_set_height(ui_left_eye, 140);
    lv_obj_set_x(ui_left_eye, -100);
    lv_obj_set_y(ui_left_eye, -50);
    lv_obj_set_align(ui_left_eye, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_left_eye, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_left_eye, 32767, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_left_eye, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_left_eye, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_right_eye = lv_obj_create(ui_ai_chat);
    lv_obj_remove_style_all(ui_right_eye);
    lv_obj_set_width(ui_right_eye, 140);
    lv_obj_set_height(ui_right_eye, 140);
    lv_obj_set_x(ui_right_eye, 100);
    lv_obj_set_y(ui_right_eye, -50);
    lv_obj_set_align(ui_right_eye, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_right_eye, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_right_eye, 32767, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_right_eye, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_right_eye, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_text = lv_label_create(ui_ai_chat);
    lv_obj_set_width(ui_chat_text, 269);
    lv_obj_set_height(ui_chat_text, 83);
    lv_obj_set_x(ui_chat_text, 3);
    lv_obj_set_y(ui_chat_text, 135);
    lv_obj_set_align(ui_chat_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_chat_text, "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    lv_obj_set_style_text_color(ui_chat_text, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chat_text, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_chat_text, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_chat_text, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chat_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chat_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chat_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chat_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_chat_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_chat_text, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_red_ring = lv_obj_create(ui_ai_chat);
    lv_obj_remove_style_all(ui_red_ring);
    lv_obj_set_width(ui_red_ring, 466);
    lv_obj_set_height(ui_red_ring, 466);
    lv_obj_set_align(ui_red_ring, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_red_ring, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_red_ring, 32767, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_red_ring, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_red_ring, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_red_ring, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_red_ring, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_red_ring, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_red_ring, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ai_chat, ui_event_ai_chat, LV_EVENT_ALL, NULL);

}

void ui_ai_chat_screen_destroy(void)
{
    if(ui_ai_chat) lv_obj_del(ui_ai_chat);

    // NULL screen variables
    ui_ai_chat = NULL;
    ui_left_eye = NULL;
    ui_right_eye = NULL;
    ui_chat_text = NULL;
    ui_red_ring = NULL;

}
