// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting
extern void ui_setting_screen_init(void);
extern void ui_setting_screen_destroy(void);
extern void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_label_date;
extern lv_obj_t * ui_label_time;
extern lv_obj_t * ui_image_volume;
extern lv_obj_t * ui_label_volume;
extern lv_obj_t * ui_slider_volume;
extern lv_obj_t * ui_container_network;
extern lv_obj_t * ui_image_network;
extern lv_obj_t * ui_container_battery;
extern lv_obj_t * ui_image_battery;
extern lv_obj_t * ui_container_gps;
extern lv_obj_t * ui_image_gps;
extern lv_obj_t * ui_label_gps;
extern lv_obj_t * ui_label_gps__number;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

