// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef UI_SOS_H
#define UI_SOS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SOS
extern void ui_SOS_screen_init(void);
extern void ui_SOS_screen_destroy(void);
extern void ui_event_SOS(lv_event_t * e);
extern lv_obj_t * ui_SOS;
extern lv_obj_t * ui_label_SOS;
extern lv_obj_t * ui_container_count_down;
extern lv_obj_t * ui_label_count_down;
extern lv_obj_t * ui_label_bottom;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

