// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#include "../ui.h"

lv_obj_t * ui_setting = NULL;
lv_obj_t * ui_label_date = NULL;
lv_obj_t * ui_label_time = NULL;
lv_obj_t * ui_image_volume = NULL;
lv_obj_t * ui_label_volume = NULL;
lv_obj_t * ui_slider_volume = NULL;
lv_obj_t * ui_container_network = NULL;
lv_obj_t * ui_image_network = NULL;
lv_obj_t * ui_container_battery = NULL;
lv_obj_t * ui_image_battery = NULL;
lv_obj_t * ui_container_gps = NULL;
lv_obj_t * ui_image_gps = NULL;
lv_obj_t * ui_label_gps = NULL;
lv_obj_t * ui_label_gps__number = NULL;
// event funtions
void ui_event_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE) {
        lv_indev_wait_release(lv_indev_active());
        setting_event_callback(e);
    }
}

// build funtions

void ui_setting_screen_init(void)
{
    if (ui_setting != NULL) {
        return;
    }

    ui_setting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_setting, lv_color_hex(0x1C90FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_date = lv_label_create(ui_setting);
    lv_obj_set_width(ui_label_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_date, 58);
    lv_obj_set_y(ui_label_date, 130);
    lv_label_set_text(ui_label_date, "1999/01/01");
    lv_obj_remove_flag(ui_label_date, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_label_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_date, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_time = lv_label_create(ui_setting);
    lv_obj_set_width(ui_label_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_time, 58);
    lv_obj_set_y(ui_label_time, 166);
    lv_label_set_text(ui_label_time, "00:00");
    lv_obj_remove_flag(ui_label_time, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_label_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_time, &ui_font_mont_82, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_volume = lv_image_create(ui_setting);
    lv_image_set_src(ui_image_volume, &ui_img_image_volume_png);
    lv_obj_set_width(ui_image_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_volume, 103);
    lv_obj_set_y(ui_image_volume, 312);
    lv_obj_add_flag(ui_image_volume, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_image_volume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_volume = lv_label_create(ui_setting);
    lv_obj_set_width(ui_label_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_volume, 127);
    lv_obj_set_y(ui_label_volume, 310);
    lv_label_set_text(ui_label_volume, "volume");
    lv_obj_remove_flag(ui_label_volume, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_label_volume, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slider_volume = lv_slider_create(ui_setting);
    lv_slider_set_value(ui_slider_volume, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slider_volume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slider_volume, 50,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_width(ui_slider_volume, 261);
    lv_obj_set_height(ui_slider_volume, 32);
    lv_obj_set_x(ui_slider_volume, 103);
    lv_obj_set_y(ui_slider_volume, 340);

    lv_obj_set_style_bg_color(ui_slider_volume, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_slider_volume, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_slider_volume, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_slider_volume, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_slider_volume, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_slider_volume, -2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_slider_volume, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_slider_volume, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_slider_volume, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_slider_volume,
                                                                                                    lv_obj_get_style_pad_right(ui_slider_volume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_container_network = lv_obj_create(ui_setting);
    lv_obj_remove_style_all(ui_container_network);
    lv_obj_set_width(ui_container_network, 66);
    lv_obj_set_height(ui_container_network, 66);
    lv_obj_set_x(ui_container_network, 342);
    lv_obj_set_y(ui_container_network, 130);
    lv_obj_remove_flag(ui_container_network,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_container_network, 32767, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_network, lv_color_hex(0x191919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_network, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_network = lv_image_create(ui_container_network);
    lv_image_set_src(ui_image_network, &ui_img_image_wififill_png);
    lv_obj_set_width(ui_image_network, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_network, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_image_network, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_image_network, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_container_battery = lv_obj_create(ui_setting);
    lv_obj_remove_style_all(ui_container_battery);
    lv_obj_set_width(ui_container_battery, 66);
    lv_obj_set_height(ui_container_battery, 66);
    lv_obj_set_x(ui_container_battery, 342);
    lv_obj_set_y(ui_container_battery, 204);
    lv_obj_remove_flag(ui_container_battery,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_container_battery, 32767, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_battery, lv_color_hex(0x191919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_battery = lv_image_create(ui_container_battery);
    lv_image_set_src(ui_image_battery, &ui_img_image_battery100_png);
    lv_obj_set_width(ui_image_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_image_battery, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_image_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_container_gps = lv_obj_create(ui_setting);
    lv_obj_remove_style_all(ui_container_gps);
    lv_obj_set_width(ui_container_gps, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_container_gps, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_container_gps, 0);
    lv_obj_set_y(ui_container_gps, 20);
    lv_obj_set_align(ui_container_gps, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_container_gps, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image_gps = lv_image_create(ui_container_gps);
    lv_image_set_src(ui_image_gps, &ui_img_image_gps_png);
    lv_obj_set_width(ui_image_gps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_gps, LV_SIZE_CONTENT);    /// 1
    lv_obj_remove_flag(ui_image_gps, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_label_gps = lv_label_create(ui_container_gps);
    lv_obj_set_width(ui_label_gps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_gps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_gps, 24);
    lv_obj_set_y(ui_label_gps, 0);
    lv_label_set_text(ui_label_gps, "GPS STATUS");
    lv_obj_set_style_text_color(ui_label_gps, lv_color_hex(0x2DDA86), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_gps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_gps, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_gps__number = lv_label_create(ui_container_gps);
    lv_obj_set_width(ui_label_gps__number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_gps__number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_gps__number, 0);
    lv_obj_set_y(ui_label_gps__number, 30);
    lv_obj_set_align(ui_label_gps__number, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_label_gps__number, "GPS NUMBER");
    lv_obj_remove_flag(ui_label_gps__number,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_label_gps__number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_gps__number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_gps__number, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_ALL, NULL);

}

void ui_setting_screen_destroy(void)
{
    if(ui_setting) lv_obj_del(ui_setting);

    // NULL screen variables
    ui_setting = NULL;
    ui_label_date = NULL;
    ui_label_time = NULL;
    ui_image_volume = NULL;
    ui_label_volume = NULL;
    ui_slider_volume = NULL;
    ui_container_network = NULL;
    ui_image_network = NULL;
    ui_container_battery = NULL;
    ui_image_battery = NULL;
    ui_container_gps = NULL;
    ui_image_gps = NULL;
    ui_label_gps = NULL;
    ui_label_gps__number = NULL;

}
