// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#include "../ui.h"
#include <stdio.h>

#include "tal_api.h"

lv_obj_t * ui_setting = NULL;
lv_obj_t * ui_image_volume = NULL;
lv_obj_t * ui_label_volume = NULL;
lv_obj_t * ui_slider_volume = NULL;
lv_obj_t * ui_container_network = NULL;
lv_obj_t * ui_image_network = NULL;
lv_obj_t * ui_container_battery = NULL;
lv_obj_t * ui_image_battery = NULL;
lv_obj_t * ui_container_gps = NULL;
lv_obj_t * ui_image_gps = NULL;
lv_obj_t * ui_label_gps = NULL;
lv_obj_t * ui_label_gps__number = NULL;
lv_obj_t * ui_container_datetime = NULL;
lv_obj_t * ui_label_date = NULL;
lv_obj_t * ui_label_time = NULL;

/* Debug control macro for volume slider */
// #define DEBUG_VOLUME_SLIDER

/* Internal volume slider event handler */
static void volume_slider_event_handler(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    
#ifdef DEBUG_VOLUME_SLIDER
    PR_DEBUG("Volume slider event: %d", code);
#endif

    if (code == LV_EVENT_RELEASED) {
        /* User released the slider, report current value */
#ifdef DEBUG_VOLUME_SLIDER
        int32_t volume = lv_slider_get_value(slider);
        PR_DEBUG("Volume released: %d", (int)volume);
#endif
        
        volume_changed_callback(e);
    }
}

// event funtions
void ui_event_setting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE) {
        lv_indev_wait_release(lv_indev_active());
        setting_event_callback(e);
    } else if (event_code == LV_EVENT_SCREEN_LOADED || event_code == LV_EVENT_SCREEN_UNLOADED) {
        setting_event_callback(e);
    }
}

// build funtions

void ui_setting_screen_init(void)
{
    if (ui_setting != NULL) {
        return;
    }

    ui_setting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_setting, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_style_bg_color(ui_setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_setting, lv_color_hex(0x1C90FC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_volume = lv_image_create(ui_setting);
    lv_image_set_src(ui_image_volume, &ui_img_image_volume_png);
    lv_obj_set_width(ui_image_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_image_volume, 103);
    lv_obj_set_y(ui_image_volume, 312);
    lv_obj_add_flag(ui_image_volume, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    // lv_obj_remove_flag(ui_image_volume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label_volume = lv_label_create(ui_setting);
    lv_obj_set_width(ui_label_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_volume, 127);
    lv_obj_set_y(ui_label_volume, 310);
    lv_label_set_text(ui_label_volume, "音量");
    // lv_obj_remove_flag(ui_label_volume, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
    //                    LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_label_volume, &font_puhui_18_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slider_volume = lv_slider_create(ui_setting);
    lv_slider_set_range(ui_slider_volume, 0, 100);
    lv_slider_set_value(ui_slider_volume, 50, LV_ANIM_OFF);
    lv_obj_set_width(ui_slider_volume, 261);
    lv_obj_set_height(ui_slider_volume, 32);
    lv_obj_set_x(ui_slider_volume, 103);
    lv_obj_set_y(ui_slider_volume, 340);

    /* Style for the main track (background/unfilled part) */
    lv_obj_set_style_bg_opa(ui_slider_volume, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_slider_volume, lv_color_hex(0x2D3E50), LV_PART_MAIN);
    lv_obj_set_style_radius(ui_slider_volume, LV_RADIUS_CIRCLE, LV_PART_MAIN);
    lv_obj_set_style_pad_ver(ui_slider_volume, -2, LV_PART_MAIN); /* Makes indicator slightly larger */

    /* Style for the indicator (filled/blue part) */
    lv_obj_set_style_bg_opa(ui_slider_volume, LV_OPA_COVER, LV_PART_INDICATOR);
    lv_obj_set_style_bg_color(ui_slider_volume, lv_color_hex(0x1E90FF), LV_PART_INDICATOR);
    lv_obj_set_style_radius(ui_slider_volume, LV_RADIUS_CIRCLE, LV_PART_INDICATOR);

    /* Style for the knob (circular white handle) */
    lv_obj_set_style_bg_opa(ui_slider_volume, LV_OPA_COVER, LV_PART_KNOB);
    lv_obj_set_style_bg_color(ui_slider_volume, lv_color_white(), LV_PART_KNOB);
    lv_obj_set_style_border_width(ui_slider_volume, 0, LV_PART_KNOB);
    lv_obj_set_style_radius(ui_slider_volume, LV_RADIUS_CIRCLE, LV_PART_KNOB);
    lv_obj_set_style_pad_all(ui_slider_volume, 10, LV_PART_KNOB); /* Makes knob larger */
    lv_obj_set_style_shadow_width(ui_slider_volume, 8, LV_PART_KNOB);
    lv_obj_set_style_shadow_color(ui_slider_volume, lv_color_black(), LV_PART_KNOB);
    lv_obj_set_style_shadow_opa(ui_slider_volume, LV_OPA_20, LV_PART_KNOB);

    /* Stop gesture events from bubbling to parent (which might consume RELEASED event) */
    lv_obj_remove_flag(ui_slider_volume, LV_OBJ_FLAG_GESTURE_BUBBLE);
    
    /* Register event callbacks: VALUE_CHANGED for smooth dragging, RELEASED for final value report */
    lv_obj_add_event_cb(ui_slider_volume, volume_slider_event_handler, LV_EVENT_RELEASED, NULL);

    ui_container_network = lv_obj_create(ui_setting);
    lv_obj_remove_style_all(ui_container_network);
    lv_obj_set_width(ui_container_network, 66);
    lv_obj_set_height(ui_container_network, 66);
    lv_obj_set_x(ui_container_network, 342);
    lv_obj_set_y(ui_container_network, 130);
    lv_obj_remove_flag(ui_container_network,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_container_network, 32767, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_network, lv_color_hex(0x191919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_network, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_network = lv_image_create(ui_container_network);
    lv_image_set_src(ui_image_network, &ui_img_image_wififill_png);
    lv_obj_set_width(ui_image_network, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_network, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_image_network, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_image_network, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    ui_setting_set_network(1, 0);

    ui_container_battery = lv_obj_create(ui_setting);
    lv_obj_remove_style_all(ui_container_battery);
    lv_obj_set_width(ui_container_battery, 66);
    lv_obj_set_height(ui_container_battery, 66);
    lv_obj_set_x(ui_container_battery, 342);
    lv_obj_set_y(ui_container_battery, 204);
    lv_obj_remove_flag(ui_container_battery,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_container_battery, 32767, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_battery, lv_color_hex(0x191919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_image_battery = lv_image_create(ui_container_battery);
    lv_image_set_src(ui_image_battery, &ui_img_image_battery100_png);
    lv_obj_set_width(ui_image_battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_image_battery, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_image_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_container_gps = lv_obj_create(ui_setting);
    lv_obj_remove_style_all(ui_container_gps);
    lv_obj_set_width(ui_container_gps, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_container_gps, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_container_gps, 0);
    lv_obj_set_y(ui_container_gps, 20);
    lv_obj_set_align(ui_container_gps, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_container_gps, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_image_gps = lv_image_create(ui_container_gps);
    lv_image_set_src(ui_image_gps, &ui_img_image_gps_png);
    lv_obj_set_width(ui_image_gps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_image_gps, LV_SIZE_CONTENT);    /// 1
    lv_obj_remove_flag(ui_image_gps, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_label_gps = lv_label_create(ui_container_gps);
    lv_obj_set_width(ui_label_gps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_gps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_gps, 24);
    lv_obj_set_y(ui_label_gps, 0);
    lv_label_set_text(ui_label_gps, "GPS 状态");
    lv_obj_set_style_text_color(ui_label_gps, lv_color_hex(0x2DDA86), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_gps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_gps, &font_puhui_18_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_gps__number = lv_label_create(ui_container_gps);
    lv_obj_set_width(ui_label_gps__number, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_gps__number, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_gps__number, 0);
    lv_obj_set_y(ui_label_gps__number, 30);
    lv_obj_set_align(ui_label_gps__number, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_label_gps__number, "0 颗卫星");
    lv_obj_remove_flag(ui_label_gps__number,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_label_gps__number, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_gps__number, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_gps__number, &font_puhui_18_2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_datetime = lv_obj_create(ui_setting);
    lv_obj_remove_style_all(ui_container_datetime);
    lv_obj_set_width(ui_container_datetime, 268);
    lv_obj_set_height(ui_container_datetime, 140);
    lv_obj_set_x(ui_container_datetime, 58);
    lv_obj_set_y(ui_container_datetime, 130);
    lv_obj_remove_flag(ui_container_datetime,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_label_date = lv_label_create(ui_container_datetime);
    lv_obj_set_width(ui_label_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_date, 0);
    lv_obj_set_y(ui_label_date, 10);
    lv_label_set_text(ui_label_date, "1999/01/01");
    lv_obj_remove_flag(ui_label_date, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_label_date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_date, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_time = lv_label_create(ui_container_datetime);
    lv_obj_set_width(ui_label_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_time, 0);
    lv_obj_set_y(ui_label_time, -10);
    lv_obj_set_align(ui_label_time, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_label_time, "00:00");
    lv_obj_remove_flag(ui_label_time, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_label_time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_time, &ui_font_mont_82, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_GESTURE, NULL);
    lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_SCREEN_LOADED, NULL);
    lv_obj_add_event_cb(ui_setting, ui_event_setting, LV_EVENT_SCREEN_UNLOADED, NULL);
}

void ui_setting_screen_destroy(void)
{
    if(ui_setting) lv_obj_del(ui_setting);

    // NULL screen variables
    ui_setting = NULL;
    ui_image_volume = NULL;
    ui_label_volume = NULL;
    ui_slider_volume = NULL;
    ui_container_network = NULL;
    ui_image_network = NULL;
    ui_container_battery = NULL;
    ui_image_battery = NULL;
    ui_container_gps = NULL;
    ui_image_gps = NULL;
    ui_label_gps = NULL;
    ui_label_gps__number = NULL;
    ui_container_datetime = NULL;
    ui_label_date = NULL;
    ui_label_time = NULL;

}

///////////////////// CUSTOM FUNCTIONS ////////////////////

/**
 * @brief Update GPS status display (icon, label, satellite count)
 * 
 * Status indicators:
 * - Invalid GPS (valid=false): Red color, "GPS 正在定位...", "0 颗卫星"
 * - Valid GPS with < 10 satellites: Orange color, "GPS 状态", "x 颗卫星"
 * - Valid GPS with >= 10 satellites: Green color, "GPS 状态", "x 颗卫星"
 * 
 * @param valid true if GPS has valid fix, false if searching
 * @param satellite_count Number of satellites in use
 */
#define GPS_TEXT_BUF_SIZE 32
static char gps_text_buf[GPS_TEXT_BUF_SIZE];

void ui_setting_update_gps_status(bool valid, uint8_t satellite_count)
{
    uint32_t color;
    const char *status_text;
    
    /* Determine color and status text based on GPS validity and satellite count */
    if (!valid) {
        /* GPS invalid - searching for fix */
        color = 0xFF0000;              /* Red */
        status_text = "GPS 正在定位...";
        satellite_count = 0;            /* Show 0 satellites when invalid */
    } else if (satellite_count < 10) {
        /* GPS valid but insufficient satellites */
        color = 0xFFA500;              /* Orange */
        status_text = "GPS 状态";
    } else {
        /* GPS valid with good satellite count */
        color = 0x00FF00;              /* Green */
        status_text = "GPS 状态";
    }
    
    /* Update GPS icon color */
    if (ui_image_gps != NULL) {
        lv_obj_set_style_image_recolor(ui_image_gps, lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_image_recolor_opa(ui_image_gps, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    
    /* Update GPS status label */
    if (ui_label_gps != NULL) {
        lv_obj_set_style_text_color(ui_label_gps, lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_text(ui_label_gps, status_text);
    }
    
    /* Update satellite count label */
    if (ui_label_gps__number != NULL) {
        memset(gps_text_buf, 0, GPS_TEXT_BUF_SIZE);
        snprintf(gps_text_buf, GPS_TEXT_BUF_SIZE, "%u 颗卫星", satellite_count);
        lv_label_set_text(ui_label_gps__number, gps_text_buf);
        lv_obj_set_style_text_color(ui_label_gps__number, lv_color_hex(color), LV_PART_MAIN | LV_STATE_DEFAULT);
        
        /* Always show satellite count */
        lv_obj_clear_flag(ui_label_gps__number, LV_OBJ_FLAG_HIDDEN);
    }
}

/**
 * @brief Set time label text
 * @param time_str Time string (e.g., "12:34")
 */
void ui_setting_set_time(const char *time_str)
{
    if (ui_label_time != NULL && time_str != NULL) {
        lv_label_set_text(ui_label_time, time_str);
    }
}

/**
 * @brief Set date label text
 * @param date_str Date string (e.g., "2025/11/05")
 */
void ui_setting_set_date(const char *date_str)
{
    if (ui_label_date != NULL && date_str != NULL) {
        lv_label_set_text(ui_label_date, date_str);
    }
}

/**
 * @brief Set volume slider value
 * @param volume Volume level (0-100)
 */
void ui_setting_set_volume(uint8_t volume)
{
    if (ui_slider_volume != NULL) {
        /* Clamp volume to 0-100 range */
        uint8_t clamped_volume = volume;
        if (clamped_volume > 100) {
            clamped_volume = 100;
        }
        
        /* Set slider value with animation */
        lv_slider_set_value(ui_slider_volume, clamped_volume, LV_ANIM_ON);
    }
}

/**
 * @brief Set network icon
 * @param network_type Network type (0: 4G, 1: WiFi, 2: Wired)
 * @param status Network status (0: No network, 1: 1 bar, 2: 2 bars, 3: 3 bars, 4: 4 bars)
 */
void ui_setting_set_network(uint8_t network_type, uint8_t status)
{
    if (ui_image_network == NULL) {
        return;
    }

    if (network_type == 0) {
        // 4G
        if (status == 1) {
            lv_image_set_src(ui_image_network, &ui_img_image_4gsignal1_png);
        } else if (status == 2) {
            lv_image_set_src(ui_image_network, &ui_img_image_4gsignal2_png);
        } else if (status == 3) {
            lv_image_set_src(ui_image_network, &ui_img_image_4gsignal3_png);
        } else if (status == 4) {
            lv_image_set_src(ui_image_network, &ui_img_image_4gfill_png);
        } else {
            lv_image_set_src(ui_image_network, &ui_img_image_4glost_png);
        }
    } else if (network_type == 1) {
        // WiFi
        lv_image_set_src(ui_image_network, &ui_img_image_wififill_png);
        if (status == 0) {
            /* No network - dim the icon by reducing opacity */
            lv_obj_set_style_opa(ui_image_network, LV_OPA_30, LV_PART_MAIN | LV_STATE_DEFAULT);
        } else {
            /* Network connected - full opacity */
            lv_obj_set_style_opa(ui_image_network, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
    } else {
        // Nothing to do
    }
}

void ui_setting_set_battery(uint8_t percentage, uint8_t is_charging)
{
    if (NULL == ui_image_battery) {
        return;
    }

    if (is_charging) {
        lv_image_set_src(ui_image_battery, &ui_img_image_battercharging_png);
        return;
    } 
    
    if (percentage <= 20) {
        lv_image_set_src(ui_image_battery, &ui_img_image_battery20_png);
    } else if (percentage <= 50) {
        lv_image_set_src(ui_image_battery, &ui_img_image_battery50_png);
    } else if (percentage <= 60) {
        lv_image_set_src(ui_image_battery, &ui_img_image_battery60_png);
    } else if (percentage <= 100) {
        lv_image_set_src(ui_image_battery, &ui_img_image_battery100_png);
    }
}
