// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_setting
extern void ui_setting_screen_init(void);
extern void ui_setting_screen_destroy(void);
extern void ui_event_setting(lv_event_t * e);
extern lv_obj_t * ui_setting;
extern lv_obj_t * ui_label_date;
extern lv_obj_t * ui_label_time;
extern lv_obj_t * ui_image_volume;
extern lv_obj_t * ui_label_volume;
extern lv_obj_t * ui_slider_volume;
extern lv_obj_t * ui_container_network;
extern lv_obj_t * ui_image_network;
extern lv_obj_t * ui_container_battery;
extern lv_obj_t * ui_image_battery;
extern lv_obj_t * ui_container_gps;
extern lv_obj_t * ui_image_gps;
extern lv_obj_t * ui_label_gps;
extern lv_obj_t * ui_label_gps__number;
// CUSTOM VARIABLES

// CUSTOM FUNCTIONS
/**
 * @brief Set GPS color (both icon and label)
 * @param rgb_color 24-bit RGB color (e.g., 0xFF0000 for red, 0x00FF00 for green)
 */
void ui_setting_set_gps_color(uint32_t rgb_color);

/**
 * @brief Update GPS satellite count
 * @param count Number of satellites
 */
void ui_setting_set_gps_count(uint8_t count);

/**
 * @brief Set time label text
 * @param time_str Time string (e.g., "12:34")
 */
void ui_setting_set_time(const char *time_str);

/**
 * @brief Set date label text
 * @param date_str Date string (e.g., "2025/11/05")
 */
void ui_setting_set_date(const char *date_str);

/**
 * @brief Set volume slider value
 * @param volume Volume level (0-100)
 */
void ui_setting_set_volume(uint8_t volume);

/**
 * @brief Set network icon
 * @param network_type Network type (0: 4G, 1: WiFi, 2: Wired)
 * @param status Network status (0: No network, 1: 1 bar, 2: 2 bars, 3: 3 bars, 4: 4 bars)
 */
void ui_setting_set_network(uint8_t network_type, uint8_t status);

/**
 * @brief Set battery icon
 * @param percentage Battery percentage (0-100)
 * @param is_charging Is charging (true: charging, false: not charging)
 */
void ui_setting_set_battery(uint8_t percentage, uint8_t is_charging);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

