// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#include "../ui.h"

lv_obj_t * ui_SOS = NULL;
lv_obj_t * ui_label_SOS = NULL;
lv_obj_t * ui_container_count_down = NULL;
lv_obj_t * ui_label_count_down = NULL;
lv_obj_t * ui_label_bottom = NULL;
// event funtions
void ui_event_SOS(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        sos_countdown_start(e);
    }
}

// build funtions

void ui_SOS_screen_init(void)
{
    if (ui_SOS != NULL) {
        return;
    }

    ui_SOS = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SOS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SOS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SOS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_SOS = lv_label_create(ui_SOS);
    lv_obj_set_width(ui_label_SOS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_SOS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_SOS, 0);
    lv_obj_set_y(ui_label_SOS, 60);
    lv_obj_set_align(ui_label_SOS, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_label_SOS, "SOS");
    lv_obj_set_style_text_color(ui_label_SOS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_SOS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_SOS, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_container_count_down = lv_obj_create(ui_SOS);
    lv_obj_remove_style_all(ui_container_count_down);
    lv_obj_set_width(ui_container_count_down, 180);
    lv_obj_set_height(ui_container_count_down, 180);
    lv_obj_set_align(ui_container_count_down, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_container_count_down, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_container_count_down, 32767, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_container_count_down, lv_color_hex(0xF04C4C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_container_count_down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_count_down = lv_label_create(ui_container_count_down);
    lv_obj_set_width(ui_label_count_down, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_count_down, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_count_down, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_count_down, "3");
    lv_obj_set_style_text_color(ui_label_count_down, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_count_down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_count_down, &ui_font_mont_82, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_bottom = lv_label_create(ui_SOS);
    lv_obj_set_width(ui_label_bottom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_bottom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_bottom, 0);
    lv_obj_set_y(ui_label_bottom, -66);
    lv_obj_set_align(ui_label_bottom, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_label_bottom, "SOS Bottom");
    lv_obj_set_style_text_color(ui_label_bottom, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_bottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_bottom, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SOS, ui_event_SOS, LV_EVENT_ALL, NULL);

}

void ui_SOS_screen_destroy(void)
{
    if(ui_SOS) lv_obj_del(ui_SOS);

    // NULL screen variables
    ui_SOS = NULL;
    ui_label_SOS = NULL;
    ui_container_count_down = NULL;
    ui_label_count_down = NULL;
    ui_label_bottom = NULL;

}
