// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef UI_TRACKER_CLOSE_H
#define UI_TRACKER_CLOSE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tracker_close
extern void ui_tracker_close_screen_init(void);
extern void ui_tracker_close_screen_destroy(void);
extern void ui_event_tracker_close(lv_event_t * e);
extern lv_obj_t * ui_tracker_close;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

