// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef UI_TRACKER_H
#define UI_TRACKER_H

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tracker
extern void ui_tracker_screen_init(void);
extern void ui_tracker_screen_destroy(void);
extern void ui_event_tracker(lv_event_t *e);
extern lv_obj_t *ui_tracker;
// CUSTOM VARIABLES

/**
 * Update tracker screen with target information
 * @param total_distance Distance from tracker to cattle in meters
 * @param heading_degrees Current compass heading in degrees (0-360, 0=North)
 * @param bearing_degrees Target bearing angle in degrees (0-360, 0=North, relative to true north)
 */
void ui_tracker_target_update(uint32_t total_distance, float heading_degrees, float bearing_degrees);

/**
 * Animate distance scale to target value with smooth transition
 * @param target_scale Target distance scale in meters
 */
void ui_tracker_animate_distance_scale(int target_scale);

/**
 * Zoom in (decrease distance scale)
 * @return true if zoom successful, false if already at minimum zoom
 */
bool ui_tracker_zoom_in(void);

/**
 * Zoom out (increase distance scale)
 * @return true if zoom successful, false if already at maximum zoom
 */
bool ui_tracker_zoom_out(void);

/**
 * Reset zoom to default level (200m)
 */
void ui_tracker_zoom_reset(void);

/**
 * Get current zoom level index
 * @return Current zoom level index (0 to 8)
 */
int ui_tracker_get_zoom_index(void);

/**
 * Get current distance scale in meters
 * @return Current distance scale in meters
 */
int ui_tracker_get_distance_scale(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
