// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#include "../ui.h"

lv_obj_t * ui_tracker_close = NULL;
// event funtions
void ui_event_tracker_close(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE) {
        lv_indev_wait_release(lv_indev_active());
        tracker_close_event_callback(e);
    }
}

// build funtions

void ui_tracker_close_screen_init(void)
{
    if (ui_tracker_close != NULL) {
        return;
    }

    ui_tracker_close = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_tracker_close, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tracker_close, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tracker_close, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_tracker_close, ui_event_tracker_close, LV_EVENT_GESTURE, NULL);

}

void ui_tracker_close_screen_destroy(void)
{
    if(ui_tracker_close) lv_obj_del(ui_tracker_close);

    // NULL screen variables
    ui_tracker_close = NULL;

}
