// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef UI_TRACKER_H
#define UI_TRACKER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_tracker
extern void ui_tracker_screen_init(void);
extern void ui_tracker_screen_destroy(void);
extern void ui_event_tracker(lv_event_t * e);
extern lv_obj_t * ui_tracker;
// CUSTOM VARIABLES

void ui_tracker_target_update(uint32_t total_distance, float heading_degrees);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

