// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef _CATTLE_PROJECT_UI_H
#define _CATTLE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_ai_chat.h"
#include "screens/ui_setting.h"
#include "screens/ui_SOS.h"
#include "screens/ui_tracker.h"
#include "screens/ui_tracker_close.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t *eyeblinking_Animation(lv_obj_t *TargetObject, int delay);
extern lv_anim_t *eyelookup_Animation(lv_obj_t *TargetObject, int delay);
extern lv_anim_t *eyelookleft_Animation(lv_obj_t *TargetObject, int delay);
extern lv_anim_t *eyelookright_Animation(lv_obj_t *TargetObject, int delay);

// EVENTS

extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern const lv_image_dsc_t ui_img_image_volume_png;       // assets/image/volume.png
extern const lv_image_dsc_t ui_img_image_wififill_png;     // assets/image/wifiFill.png
extern const lv_image_dsc_t ui_img_image_battery100_png;   // assets/image/battery100.png
extern const lv_image_dsc_t ui_img_image_gps_png;          // assets/image/GPS.png
extern const lv_image_dsc_t ui_img_image_search_scope_png; // assets/image/search_scope.png
extern const lv_image_dsc_t ui_img_image_cattle_icon_png;  // assets/image/cattle_icon.png

// FONTS
LV_FONT_DECLARE(ui_font_mont_82);
LV_FONT_DECLARE(font_puhui_30_4);
LV_FONT_DECLARE(font_puhui_18_2);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
