// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#include "ui.h"

#include "app_ui_main.h"
#include "app_ui_func.h"
#include "app_encoder.h"
#include "app_volume.h"
#include "tal_api.h"

void sos_countdown_finish(lv_event_t * e)
{
    // Your code here
    app_sos_start();
}

void sos_cancel_clicked(lv_event_t * e)
{
    // Notify external code that cancel button was clicked
    PR_DEBUG("SOS cancel button clicked");
    app_sos_stop();
}

void ai_chat_event_callback(lv_event_t * e)
{
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    PR_DEBUG("Gesture direction: %d", dir);
    if (dir == LV_DIR_LEFT) {
        app_page_load(&tracker_page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0);
    } else if (dir == LV_DIR_BOTTOM) {
        app_page_load(&setting_page, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 0);
    }
}

void setting_event_callback(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if (event_code == LV_EVENT_SCREEN_LOADED) {
        app_ui_func_setting_load_callback();
    } else if (event_code == LV_EVENT_SCREEN_UNLOADED) {
        app_ui_func_setting_unload_callback();
    } else if (event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if (dir == LV_DIR_TOP) {
            app_page_back(LV_SCR_LOAD_ANIM_MOVE_TOP, 0);
        }
    }
}

void volume_changed_callback(lv_event_t * e)
{
    lv_obj_t * slider = lv_event_get_target(e);
    int32_t volume = lv_slider_get_value(slider);
    
    PR_DEBUG("Volume changed: %d", (int)volume);
    
    /* Call app_volume_set which handles async execution internally */
    app_volume_set((uint8_t)volume);
}

void tracker_event_callback(lv_event_t * e)
{
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    if (dir == LV_DIR_RIGHT) {
        app_page_back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0);
    } else if (dir == LV_DIR_BOTTOM) {
        app_page_load(&setting_page, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 0);
    }
}

void tracker_close_event_callback(lv_event_t * e)
{
    // Your code here
}
