// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#include "ui.h"

#include "app_ui_main.h"
#include "tal_api.h"

void sos_countdown_start(lv_event_t * e)
{
    // Your code here
}

void ai_chat_event_callback(lv_event_t * e)
{
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    PR_DEBUG("Gesture direction: %d", dir);
    if (dir == LV_DIR_LEFT) {
        app_page_load(&tracker_page, LV_SCR_LOAD_ANIM_MOVE_LEFT, 0);
    } else if (dir == LV_DIR_BOTTOM) {
        app_page_load(&setting_page, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 0);
    }
}

void setting_event_callback(lv_event_t * e)
{
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    if (dir == LV_DIR_TOP) {
        app_page_back(LV_SCR_LOAD_ANIM_MOVE_TOP, 0);
    }
}

void tracker_event_callback(lv_event_t * e)
{
    lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
    if (dir == LV_DIR_RIGHT) {
        app_page_back(LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0);
    }
}

void tracker_close_event_callback(lv_event_t * e)
{
    // Your code here
}
