// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: cattle_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ai_chat_event_callback(lv_event_t * e);
void setting_event_callback(lv_event_t * e);
void sos_countdown_start(lv_event_t * e);
void tracker_event_callback(lv_event_t * e);
void tracker_close_event_callback(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
